# Generated by Django 2.2.19 on 2022-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220725_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bondins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=50)),
            ],
        ),
    ]
